repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.2  # Use the latest stable version
    hooks:
      - id: gitleaks
        args: ["detect", "--source=.", "--no-banner", "--redact"]
